### ISSUE TITLE
Umlaut issues when using Asiciidoctor-pdf with dita

### ISSUE THREAD

**Issue by Clemi81** [asciidoctor/asciidoctor-pdf#1000]
Hello folks,

I use Asciidoctor-Diagram with ditaa to draw diagrams for my documentation. 

Preview with Firefox-Plugin works well. However, when I create the diagram via asciidoctor-pdf, all Umlauts are replaced by squares. 
In the rest of the documentation all Umlauts are shown correctly. Therefore I assume there is some message missing in the diagram that tells the compiler to choose correct encoding.

Thank you for your support.

Clemi

**Comment by habamax** [comment]
It is not only umlauts it is generally all unicode text (I belive).

**Comment by mojavelinux** [comment]
It really depends on your font setup. If you have a fallback font, and the fallback font has those characters, it will find the glyphs. If it can't find the glyph, you are either going to blank or something other than what you expect.

See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#fonts

Also, keep in mind that the default theme no longer provides a fallback font (because it turns out to really slow down conversion). But it's still available if you set the theme to default-with-fallback-font (e.g., `-a pdf-theme=default-with-fallback-font`).

**Comment by habamax** [comment]
Not really, fallback font is not the case (I have it properly setup).
The thing is that asciidoctor-diagram process ditaa data in a manner that trash unicode chars. It might be connected with how in Windows text is passed to a subprogram in some cp1251 encoding instead of UTF-8 or maybe something else.

And strangely ditaa with unicode works just fine in firefox asciidoctor.js.

**Comment by habamax** [comment]
So the issue is not only asciidoctor-pdf + asciidoctor-diagram. It is also a regular asciidoctor to html.

## test data
== test 1
// 2019-04-22
Press the button kbd:[Alt+F4]

```
[ditaa, test-ditaa, png]
....
/--------\   +-------+
|cAAA    +---+Version|
|  прив  |   |   V3  |
|  Base  |   |cRED{d}|
|     {s}|   +-------+
\---+----/
....
```

## PDF output
![image](https://user-images.githubusercontent.com/234774/61030274-b7db5400-a3c5-11e9-9422-dbdbe0e23958.png)

## HTML output

![image](https://user-images.githubusercontent.com/234774/61030298-c6c20680-a3c5-11e9-90b6-ac431ec6a2f6.png)

## asciidoctor.js output
![image](https://user-images.githubusercontent.com/234774/61030344-db060380-a3c5-11e9-8ec7-77d2bdaed10b.png)

**Comment by mojavelinux** [comment]
Ah, I see.

Then this is an Asciidoctor Diagram issue, it seems. Asciidoctor PDF just inserts the diagram that Asciidoctor Diagram creates, so there's nothing really that Asciidoctor PDF is doing here. You could also check the cached file that Asciidoctor Diagram creates to verify it is already corrupt at that point.

(ditaa processing in Asciidoctor.js uses different stack, so it's not the same situation).

**Comment by mojavelinux** [comment]
Thanks for verifying, @habamax.

(And keep in mind, diagrams in Asciidoctor.js are using a completely different library, so how it operates is not relevant in this context...aside from verifying that the diagram code itself is valid).

**Comment by mojavelinux** [comment]
Perhaps this is already solved by this issue? https://github.com/asciidoctor/asciidoctor-diagram/issues/150

If not, feel free to reopen another in Asciidoctor Diagram with more information.

**Comment by habamax** [comment]
I have all gems updated including asciidoctor-diagram -- so it looks that it is not fixed, at least not for windows. (I have 1.5.18 version of asciidoctor-diagram installed)

But anyway I don't use ditaa at all (I have tried it but end up either with plantuml or plain png/svg  embedding) so for me it is only slightly relevant.

**Comment by mojavelinux** [comment]
It would still be very useful if we let Pepijn know this is still an issue so it can be addressed, if possible / necessary. That way, we can close this issue here (since the relevant code is not in this repo).

**Comment by habamax** [comment]
made a comment there

**Comment by mojavelinux** [comment]
Thanks! We'll continue the conversation there.
