### ISSUE TITLE
Cross references don't jump to linked section

### ISSUE THREAD

**Issue by cfeddersen** [asciidoctor/asciidoctor-pdf#56]
I tried asciidoctor-pdf today. It's looking really nice on my sample document!
One thing I noticed is that cross references are clickable within the pdf, but the user isn't taken to the target. I'm not 100% sure if cross references should already work or not.

Using asciidoctor-pdf-1.5.0.alpha.5 and a slightly modified example.adoc, see below.

```AsciiDoc
= Document Title
Doc Writer <doc@example.com>
:doctype: book
:source-highlighter: coderay
:listing-caption: Listing

A simple cross reference <<Introduction>>.



== Introduction

A paragraph followed by a simple list with square bullets.

[square]
* item 1
* item 2


Here's how you say "`Hello, World!`" in Prawn:

.Create a basic PDF document using Prawn
[source,ruby]
----
require 'prawn'

Prawn::Document.generate 'example.pdf' do
  text 'Hello, World!'
end
----
```

**Comment by plaindocs** [comment]
I just ran into this also using

Asciidoctor 1.5.2 [http://asciidoctor.org]
Runtime Environment (ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]) (lc:US-ASCII fs:US-ASCII in:- ex:US-ASCII)

So here is a +1 for a fix. ;-)

**Comment by plaindocs** [comment]
In fact, linking to section IDs does not work for me either.

**Comment by rlopez133** [comment]
The David Gamba's quick fix works for the most part except it doesn't work if you make a cross reference to a table. The link to the table shows but when you click it, it doesn't work.

**Comment by mojavelinux** [comment]
We'll need to implement the same anchor logic for blocks as we are currently doing for sections. Then, with the fix by @DavidGamba, all the xrefs should start working. Definitely a top priority item to get addressed as soon as I get into Asciidoctor PDF work again (soonish).

**Comment by mojavelinux** [comment]
> In fact, linking to section IDs does not work for me either.

David's patch made me realize that we are using the wrong attribute to get the xref target. We have to use a combination of what we use for the DocBook and HTML5 backend to get what we want. I'll submit a patch shortly.

**Comment by mojavelinux** [comment]
I'd like to scope this issue to xrefs to sections and deal with the xrefs to arbitrary blocks in a separate issue.

**Comment by mojavelinux** [comment]
I believe this is now fixed (for sections). Please check using git master. Feel free to reopen if there are still issues.

**Comment by saleemjaffer** [comment]
I am still facing some issues with this. [#809](https://github.com/asciidoctor/asciidoctor-pdf/issues/809)

**Comment by gueggel** [comment]
Same issue here...

Asciidoctor 1.5.7.1 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]) (lc:CP850 fs:Windows-1252 in:CP850 ex:CP850)
