### ISSUE TITLE
UTF-8 regexp warnings

### ISSUE THREAD

**Issue by ysb33r** [asciidoctor/asciidoctor-pdf#69]
I am seeing these warnings appear when run from asciidoctor-gradle-plugin

```
.../asciidoctorj-pdf-1.5.0-alpha.6.jar!/gems/pdf-core-0.2.5/lib/pdf/core/pdf_object.rb:55 warning: regexp match /.../n against to UTF-8 string
```

**Comment by mojavelinux** [comment]
Turns out this was a bug in Asciidoctor PDF. When setting the value of a PDF metadata field, the content must be encoded if it includes glyphs that fall outside the WINANSI code set. We now check for this and encode the value properly.

**Comment by mojavelinux** [comment]
This was resolved by https://github.com/asciidoctor/asciidoctor-pdf/commit/0310c3e79c1cd7064c4a629a7d4f3ba82e1920d1.

**Comment by orloffm** [comment]
I am still getting 
```
pdf-core-0.6.0/lib/pdf/core/pdf_object.rb:61: warning: regexp match /.../n against to UTF-8 string
```
 when compiling this file:
```
TEST
====

== Проверка
```
Notepad2 says the file is "UTF8 Signature". Asciidoctor-pdf has version asciidoctor-pdf-1.5.0.alpha.9. And I am on Windows.

**Comment by mojavelinux** [comment]
@orloffm I've filed a separate issue to track this. Please is #308. It doesn't seem to break the operation of the xref, so I'd say that the warning is harmless. Regardless, it will be good to get it cleared up.
